### PR TITLE
Add Purple Yolk as a supported dependency

### PR DESCRIPTION
**Pull request by tfausak**
My [Purple Yolk](https://marketplace.visualstudio.com/items?itemName=taylorfausak.purple-yolk) extension can be used with Haskutil to populate warnings and errors.

### CODE REVIEW

**Comment by EduardSergeev** [comment]
Purple Yolk does not seem to work out of the box. On a simple Stack projects it pops up this:
image  
The extension log contains the following:

```text
2023-08-24T22:12:18.241Z [4df0] Activating purple-yolk version 0.10.1 ...
2023-08-24T22:12:18.245Z [4d7d] Starting interpreter ...
2023-08-24T22:12:18.245Z [4d7d] Running "cabal repl --repl-options -ddump-json" in "/home/edka/work/haskell/debug" ...
2023-08-24T22:12:18.251Z [4d7d] [stdin] :set prompt "{- purple-yolk 0.10.1 4d7d -}\n"
2023-08-24T22:12:18.252Z [4df0] Successfully activated in 0.011 seconds.
2023-08-24T22:12:18.258Z [4d7d] [stderr] /bin/sh: 1: cabal: not found
2023-08-24T22:12:18.259Z [4d7d] Error: Interpreter exited with 127!
2023-08-24T22:12:25.368Z [3dfc] Reloading interpreter ...
2023-08-24T22:12:25.368Z [3dfc] Ignoring because 4d7d is running.
2023-08-24T22:12:25.370Z [08cc] Linting src/UnusedImportProvider.hs ...
2023-08-24T22:12:25.371Z [08cc] Running "hlint --json --no-exit-code -" in "/home/edka/work/haskell/debug" ...
2023-08-24T22:12:25.381Z [08cc] [stderr] /bin/sh: 1: hlint: not found
2023-08-24T22:12:25.381Z [08cc] Error: Linter exited with 127!
```

Looks like it requires `hlint` to be installed for some reason?

**Comment by tfausak** [comment]
It tries to lint files automatically when they're saved. Everything still works even if linting fails. It will show an error to the user though. 

Also note that `cabal` wasn't found either, which is required for the default configuration. 

I mostly use this extension myself, so I haven't put much effort into making the configuration work seamlessly out of the box. Perhaps this is good motivation to do that 😄

**Comment by EduardSergeev** [comment]
> Also note that `cabal` wasn't found either, which is required for the default configuration.

I tried it with Stack project, I thought Stack was supported.
What would be the minimal Haskell project on which this extension works out of the box?

For example [Simple GHC](https://marketplace.visualstudio.com/items?itemName=dramforever.vscode-ghc-simple) which I prefer works with Cabal, Stack and even just a single `*.hs` file. In fact [this project integration tests](https://github.com/EduardSergeev/vscode-haskutil/actions/runs/5968725273/job/16194993431#step:6:78) use Simple GHC to report diagnostics on a single `*.hs` file.

**Comment by tfausak** [comment]
Stack is supported, but it must be configured. Out of the box, Purple Yolk should work with a Haskell package using `cabal`. Purple Yolk is designed to work with projects/packages, not individual Haskell files, although I may be able to add support for that. 

Feel free to close this, since I've got my work cut out for me improving the configuration of Purple Yolk. Perhaps another way to accomplish this would be to allow the user to ignore this warning. I don't mind seeing it pop up once, but it's a bit annoying to see it every time I open a workspace.

**Comment by EduardSergeev** [comment]
> Stack is supported, but it must be configured.

I managed to make it work with "Stack + Cabal" project but this configuration was trying to open `*.hs` files using invalid path (so I could not test this extension with it), see https://github.com/tfausak/purple-yolk/issues/43

> Feel free to close this, since I've got my work cut out for me improving the configuration of Purple Yolk. Perhaps another way to accomplish this would be to allow the user to ignore this warning. I don't mind seeing it pop up once, but it's a bit annoying to see it every time I open a workspace.

Yes, I am not going to add Purple Yolk to the list of supported extensions just now (maybe later when it is more of production quality) but I did add new setting `haskutil.checkDiagnosticsExtension` via #56 (available in [0.11.0](https://github.com/EduardSergeev/vscode-haskutil/releases/tag/0.11.0)) which can be used to suppress dependent extension check on start up.  
For convenience it is accessible via link added to extension check warning popup window:

image

**Comment by EduardSergeev** [comment]
Yet another way to avoid warning notification due to non-supported Haskell diagnostics generating extension is to make it supported by adding it to recently added (via #64, available in [0.12.0](https://github.com/EduardSergeev/vscode-haskutil/releases/tag/0.12.0)) new configuration setting: [haskutil.supportedDependencies](https://github.com/EduardSergeev/vscode-haskutil/blob/7cf14dfa0a2dbbb422d63e9d53d2df555fffb509/package.json#L178-L209).

**Pull request closed without merging**
